apps/quotes/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
   	url(r'^favorite/(?P<id>\d+)$', views.favorite, name='favorite'),
   	url(r'^remove/(?P<id>\d+)$', views.remove, name='remove'),
    url(r'^create?$', views.create, name='create'),
    url(r'^logout?$', views.logout, name='logout'),
    url(r'^user/(?P<id>\d+)$', views.user, name='user'),
    url(r'^$', views.index, name='index'),    
]

exam1/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.login_reg_app.urls', namespace ="login")),
    url(r'^quotes/', include('apps.quotes.urls', namespace ="quotes")),

]

apps/quotes/models.py
from __future__ import unicode_literals

from django.db import models
from ..login_reg_app.models import User

# Create your models here.

class Quote(models.Model):
    quote = models.CharField(max_length=45)
    author = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    submitter = models.ForeignKey(User)



class Favorite(models.Model):
    user = models.ForeignKey(User)
    quote = models.ForeignKey(Quote)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

apps/quotes/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from .models import Quote, Favorite 
from ..login_reg_app.models import User
from django.db.models import Count
from django.contrib import messages


# Create your views here.
def index(request):
    print "Got quote index"
    try:
        request.session['goodtogo']
    except KeyError:
        print "invalid user"  
        return redirect (reverse('login:index'))  
      
    if request.session['goodtogo']:
        print "we are goodtogo"
        u1=User.objects.get(id=request.session['id'])
        quotes = Quote.objects.all()
        favorites= Favorite.objects.filter(user=u1)
        
        context = {
            'quotes': quotes,
            'favorites': favorites
        }
        return render(request, 'quotes/index.html', context)

    else:
        print "invalid user"  
        return redirect (reverse('login:index'))  

def create(request):
    print "Got create"
    try:
        request.session['goodtogo']
    except KeyError:
        print "invalid user"  
        return redirect (reverse('login:index')) 

    if request.method == "POST" and request.session['goodtogo']:
        print "Got create post" 
        quote = request.POST['quote']
        author = request.POST['author']          
        print author
        print quote 

        if not author:
            messages.add_message(request, messages.INFO, "Need to include Author's name.")
            error=True        
        if not quote:
            messages.add_message(request, messages.INFO,"Quote cannot be blank!")
            error=True
    
        if not error: 
            u1=User.objects.get(id=request.session['id'])
            q1 = Quote(author=author, quote=quote, submitter=u1)
            q1.save()            
            return redirect (reverse('quotes:index'))
        else:
            messages.add_message(request, messages.INFO, "Please try again")
            print"we got error messages"
            return redirect (reverse('login:index')) 

def favorite(request, id):
    print "in favorite, quote id=", id
    try:
        request.session['goodtogo']
    except KeyError:
        print "invalid user"  
        return redirect (reverse('login:index')) 

    if request.session['goodtogo']:
        u1=User.objects.get(id=request.session['id'])
        q1=Quote.objects.get(id=id)
        f1= Favorite(user=u1, quote=q1)
        f1.save()
        return redirect (reverse('quotes:index'))
    else:
        print "invalid user"  
        return redirect (reverse('login:index'))      

def remove(request, id):
    print "in remove, quote id=", id
    try:
        request.session['goodtogo']
    except KeyError:
        print "invalid user"  
        return redirect (reverse('login:index')) 

    if request.session['goodtogo']:
        u1=User.objects.get(id=request.session['id'])
        q1=Quote.objects.get(id=id)
        Favorite.objects.filter(user=u1, quote=q1).delete()
        return redirect (reverse('quotes:index'))
    else:
        print "invalid user"  
        return redirect (reverse('login:index'))  



def user(request, id): 
    print "Got user"    

    try:
        request.session['goodtogo']
    except KeyError:
        print "Invalid User"  
        return redirect (reverse('login:index')) 
    print "request.session['goodtogo']", request.session['goodtogo']

    if request.session['goodtogo']: 

        # u1 = User.objects.get(id=id)
        u1 = User.objects.filter(id=id).annotate(num_postings = Count('quote'))    
        q1 = Quote.objects.filter(submitter=u1)      
        
        context = {
            'user': u1[0], 
            'quotes': q1
            }    
        return render(request, 'quotes/show_user.html', context)

    else:
        print "..invalid user"  
        return redirect (reverse('login:index'))  


def logout(request):
    request.session['goodtogo'] = False
    return redirect (reverse('login:index'))

apps/quotes/templates/quotes/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Quotes Home</title>
<meta charset="utf-8">
	<!-- Latest boostrap compiled and minified CSS -->
<!-- 	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"> -->
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'quote_app/css/style.css' %}">
</head>
<body>
<div id="container">
<div id="navbar">
      <ul>
        <li><a href="{% url 'quotes:logout' %}">Logout</a></li>
      </ul>
      <h2>Welcome {{ request.session.alias }}!</h2>
 </div> <!-- end navbar -->
    <div id='wrapper'>
  	<h2>Quotable Quotes:</h2>
        {% for quote in quotes %}
          <p>{{ quote.author }}: {{quote.quote}}    
          <p>Posted by <a href="">{{ quote.submitter.alias }}</a></p> 
          <a href="{% url 'quotes:favorite' id=quote.id %}">Add To My List</a>
        {% endfor %}
    <div id="favorites">
    <h2>My Favorites</h2>
     {% for favorite in favorites %}
      <p>{{ favorite.quote.author }}: {{favorite.quote.quote}}</p> 
          <p>Posted by <a href="{% url 'quotes:user' id=favorite.user.id %}">{{ favorite.user.alias }}</a></p> 
          <a href="{% url 'quotes:remove' id=favorite.quote.id %}">Remove From My List</a>
     {% endfor %}
      
    </div> <!-- end favorites -->
 
    <div id="form_area">
      <form action="{% url 'quotes:create' %} " method="post" id="quote_form">
        {% csrf_token %}    
        <h3>Contribute a Quote:</h3>
        <label>Quoted by:</label>
        <input type="text" name="author"><br>
        <label>Message</label>
        <textarea rows="4" cols="45" name="quote" form="quote_form"></textarea><br>


        <button type="submit" class="btn btn-primary" form="quote_form" value="Submit">Submit Quote</button>
      </form>   
      <div id='errors'> 
        {% for error in errors %}
        <p> {{ error }} </p>
        {% endfor %}
      </div>
    </div> <!-- end wrapper -->
  </div> <!-- end container -->
  
</body>
</html>

apps/quotes/templates/quotes/show_user.html
<!DOCTYPE html>
<html>
<head>
	<title>User Profile</title>
<meta charset="utf-8">
	
</head>
<body>
<div id="container">
<div id="navbar">
      <ul>
        <li><a href=" {% url 'quotes:index' %} ">Dashboard</a></li>
        <li><a href="{% url 'quotes:logout' %}">Logout</a></li> 
      </ul>
 </div> <!-- end navbar -->
    <div id='wrapper'>
    <h3>Posts by {{user.alias}}:</h3>
    <h3>Count: {{ user.num_postings }}
    <div id="quotes_area">
        {% for quote in quotes %}
            <p>{{quote.author}}: {{quote.quote}}</p>
        {% endfor %} 
    </div>   
    </div> <!-- end wrapper -->
  </div> <!-- end container -->  
</body>
</html>